// <auto-generated />
using System;
using BanQuanAu1.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuanApi.Migrations
{
    [DbContext(typeof(BanQuanAu1DbContext))]
    [Migration("20250907190442_diachiback")]
    partial class diachiback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.Property<Guid>("IDKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanApi.Data.AnhSanPham", b =>
                {
                    b.Property<Guid>("IDAnhSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LaAnhChinh")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaAnh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("UrlAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IDAnhSanPham");

                    b.HasIndex("IDSanPhamChiTiet");

                    b.ToTable("AnhSanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("QuanApi.Data.ChatLieu", b =>
                {
                    b.Property<Guid>("IDChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaChatLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDChatLieu");

                    b.ToTable("ChatLieus");
                });

            modelBuilder.Entity("QuanApi.Data.ChiTietGioHang", b =>
                {
                    b.Property<Guid>("IDChiTietGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IDGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaChiTietGioHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDChiTietGioHang");

                    b.HasIndex("IDGioHang");

                    b.HasIndex("IDSanPhamChiTiet");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("QuanApi.Data.ChiTietHoaDon", b =>
                {
                    b.Property<Guid>("IDChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IDHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaChiTietHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDChiTietHoaDon");

                    b.HasIndex("IDHoaDon");

                    b.HasIndex("IDSanPhamChiTiet");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.DanhMuc", b =>
                {
                    b.Property<Guid>("IDDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("QuanApi.Data.DiaChi", b =>
                {
                    b.Property<Guid>("IDDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiChiTiet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LaMacDinh")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SdtNguoiNhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDDiaChi");

                    b.HasIndex("IDKhachHang");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("QuanApi.Data.DotGiamGia", b =>
                {
                    b.Property<Guid>("IDDotGiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaDot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenDot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDDotGiamGia");

                    b.ToTable("DotGiamGias");
                });

            modelBuilder.Entity("QuanApi.Data.GioHang", b =>
                {
                    b.Property<Guid>("IDGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaGioHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDGioHang");

                    b.HasIndex("IDKhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("QuanApi.Data.HoaDon", b =>
                {
                    b.Property<Guid>("IDHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDPhieuGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDPhuongThucThanhToan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("LyDoHuyDon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PhiVanChuyen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoaDon")
                        .HasColumnType("bit");

                    b.HasKey("IDHoaDon");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVien");

                    b.HasIndex("IDPhieuGiamGia");

                    b.HasIndex("IDPhuongThucThanhToan");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.HoaTiet", b =>
                {
                    b.Property<Guid>("IDHoaTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaHoaTiet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenHoaTiet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDHoaTiet");

                    b.ToTable("HoaTiet");
                });

            modelBuilder.Entity("QuanApi.Data.KhachHangPhieuGiam", b =>
                {
                    b.Property<Guid>("IDKhachHangPhieuGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDPhieuGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaKhachHangPhieuGiam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDaSuDung")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDKhachHangPhieuGiam");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDPhieuGiamGia");

                    b.ToTable("KhachHangPhieuGiams");
                });

            modelBuilder.Entity("QuanApi.Data.KichCo", b =>
                {
                    b.Property<Guid>("IDKichCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaKichCo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenKichCo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDKichCo");

                    b.ToTable("KichCos");
                });

            modelBuilder.Entity("QuanApi.Data.KieuDang", b =>
                {
                    b.Property<Guid>("IDKieuDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaKieuDang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenKieuDang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDKieuDang");

                    b.ToTable("KieuDangs");
                });

            modelBuilder.Entity("QuanApi.Data.LichSuHoaDon", b =>
                {
                    b.Property<Guid>("IDLichSuHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IDHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaLichSuHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiLichSu")
                        .HasColumnType("bit");

                    b.HasKey("IDLichSuHoaDon");

                    b.HasIndex("IDHoaDon");

                    b.ToTable("LichSuHoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.LoaiOng", b =>
                {
                    b.Property<Guid>("IDLoaiOng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaLoaiOng")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenLoaiOng")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDLoaiOng");

                    b.ToTable("LoaiOngs");
                });

            modelBuilder.Entity("QuanApi.Data.LungQuan", b =>
                {
                    b.Property<Guid>("IDLungQuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaLungQuan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenLungQuan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDLungQuan");

                    b.ToTable("LungQuans");
                });

            modelBuilder.Entity("QuanApi.Data.MauSac", b =>
                {
                    b.Property<Guid>("IDMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaMauSac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDMauSac");

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("QuanApi.Data.NhanVien", b =>
                {
                    b.Property<Guid>("IDNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IDVaiTro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDNhanVien");

                    b.HasIndex("IDVaiTro");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QuanApi.Data.PhieuGiamGia", b =>
                {
                    b.Property<Guid>("IDPhieuGiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DonToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GiaTriGiam")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaTriGiamToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("LaCongKhai")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("SoLuong")
                        .HasColumnType("smallint");

                    b.Property<string>("TenPhieu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDPhieuGiamGia");

                    b.ToTable("PhieuGiamGias");
                });

            modelBuilder.Entity("QuanApi.Data.PhongTroChuyen", b =>
                {
                    b.Property<Guid>("IDPhongTroChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaPhongTroChuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDPhongTroChuyen");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVien");

                    b.ToTable("PhongTroChuyens");
                });

            modelBuilder.Entity("QuanApi.Data.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("IDPhuongThucThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaPhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDPhuongThucThanhToan");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("QuanApi.Data.SanPham", b =>
                {
                    b.Property<Guid>("IDSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CoGian")
                        .HasColumnType("bit");

                    b.Property<bool>("CoXepLy")
                        .HasColumnType("bit");

                    b.Property<Guid>("IDChatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDDanhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDKieuDang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDLoaiOng")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDLungQuan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDThuongHieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDSanPham");

                    b.HasIndex("IDChatLieu");

                    b.HasIndex("IDDanhMuc");

                    b.HasIndex("IDKieuDang");

                    b.HasIndex("IDLoaiOng");

                    b.HasIndex("IDLungQuan");

                    b.HasIndex("IDThuongHieu");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IDSanPhamChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("IDDotGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDHoaTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDKichCo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaSPChiTiet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QRCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDSanPhamChiTiet");

                    b.HasIndex("IDDotGiamGia");

                    b.HasIndex("IDHoaTiet");

                    b.HasIndex("IDKichCo");

                    b.HasIndex("IDMauSac");

                    b.HasIndex("IDSanPham");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamDotGiam", b =>
                {
                    b.Property<Guid>("IDSanPhamDotGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("IDDotGiamGia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaSanPhamDotGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDSanPhamDotGiam");

                    b.HasIndex("IDDotGiamGia");

                    b.HasIndex("IDSanPhamChiTiet");

                    b.ToTable("SanPhamDotGiams");
                });

            modelBuilder.Entity("QuanApi.Data.ThuongHieu", b =>
                {
                    b.Property<Guid>("IDThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaThuongHieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDThuongHieu");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("QuanApi.Data.TinNhan", b =>
                {
                    b.Property<Guid>("IDTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IDNhanVien")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDPhongTroChuyen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaTinNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDTinNhan");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVien");

                    b.HasIndex("IDPhongTroChuyen");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("QuanApi.Data.VaiTro", b =>
                {
                    b.Property<Guid>("IDVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IDVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("QuanApi.Data.AnhSanPham", b =>
                {
                    b.HasOne("QuanApi.Data.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("IDSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("QuanApi.Data.ChiTietGioHang", b =>
                {
                    b.HasOne("QuanApi.Data.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("IDGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("IDSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("QuanApi.Data.ChiTietHoaDon", b =>
                {
                    b.HasOne("QuanApi.Data.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IDHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IDSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("QuanApi.Data.DiaChi", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanApi.Data.GioHang", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("GioHangs")
                        .HasForeignKey("IDKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanApi.Data.HoaDon", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDKhachHang");

                    b.HasOne("QuanApi.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDNhanVien");

                    b.HasOne("QuanApi.Data.PhieuGiamGia", "PhieuGiamGia")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDPhieuGiamGia");

                    b.HasOne("QuanApi.Data.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDPhuongThucThanhToan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("PhieuGiamGia");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("QuanApi.Data.KhachHangPhieuGiam", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("KhachHangPhieuGiams")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.PhieuGiamGia", "PhieuGiamGia")
                        .WithMany("KhachHangPhieuGiams")
                        .HasForeignKey("IDPhieuGiamGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("PhieuGiamGia");
                });

            modelBuilder.Entity("QuanApi.Data.LichSuHoaDon", b =>
                {
                    b.HasOne("QuanApi.Data.HoaDon", "HoaDon")
                        .WithMany("LichSuHoaDons")
                        .HasForeignKey("IDHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanApi.Data.NhanVien", b =>
                {
                    b.HasOne("QuanApi.Data.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("IDVaiTro");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanApi.Data.PhongTroChuyen", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("PhongTroChuyens")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.NhanVien", "NhanVien")
                        .WithMany("PhongTroChuyens")
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanApi.Data.SanPham", b =>
                {
                    b.HasOne("QuanApi.Data.ChatLieu", "ChatLieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.KieuDang", "KieuDang")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDKieuDang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.LoaiOng", "LoaiOng")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDLoaiOng")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.LungQuan", "LungQuan")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDLungQuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("KieuDang");

                    b.Navigation("LoaiOng");

                    b.Navigation("LungQuan");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamChiTiet", b =>
                {
                    b.HasOne("QuanApi.Data.DotGiamGia", "DotGiamGia")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDDotGiamGia");

                    b.HasOne("QuanApi.Data.HoaTiet", "HoaTiet")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDHoaTiet");

                    b.HasOne("QuanApi.Data.KichCo", "KichCo")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDKichCo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.MauSac", "MauSac")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DotGiamGia");

                    b.Navigation("HoaTiet");

                    b.Navigation("KichCo");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamDotGiam", b =>
                {
                    b.HasOne("QuanApi.Data.DotGiamGia", "DotGiamGia")
                        .WithMany("SanPhamDotGiams")
                        .HasForeignKey("IDDotGiamGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamDotGiams")
                        .HasForeignKey("IDSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DotGiamGia");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("QuanApi.Data.TinNhan", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("TinNhans")
                        .HasForeignKey("IDKhachHang");

                    b.HasOne("QuanApi.Data.NhanVien", "NhanVien")
                        .WithMany("TinNhans")
                        .HasForeignKey("IDNhanVien");

                    b.HasOne("QuanApi.Data.PhongTroChuyen", "PhongTroChuyen")
                        .WithMany("TinNhans")
                        .HasForeignKey("IDPhongTroChuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("PhongTroChuyen");
                });

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");

                    b.Navigation("KhachHangPhieuGiams");

                    b.Navigation("PhongTroChuyens");

                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("QuanApi.Data.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.DotGiamGia", b =>
                {
                    b.Navigation("SanPhamChiTiets");

                    b.Navigation("SanPhamDotGiams");
                });

            modelBuilder.Entity("QuanApi.Data.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("QuanApi.Data.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("LichSuHoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.HoaTiet", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.KieuDang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.LoaiOng", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.LungQuan", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhongTroChuyens");

                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("QuanApi.Data.PhieuGiamGia", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("KhachHangPhieuGiams");
                });

            modelBuilder.Entity("QuanApi.Data.PhongTroChuyen", b =>
                {
                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("QuanApi.Data.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamChiTiet", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("SanPhamDotGiams");
                });

            modelBuilder.Entity("QuanApi.Data.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.VaiTro", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
