// <auto-generated />
using System;
using BanQuanAu1.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace QuanApi.Migrations
{
    [DbContext(typeof(BanQuanAu1DbContext))]
    [Migration("20260403075454_AddInventoryReservationState")]
    partial class AddInventoryReservationState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.Property<Guid>("IDKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("IDHangKhachHang")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SoDiemHienTai")
                        .HasColumnType("integer");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TongDiemTichLuy")
                        .HasColumnType("integer");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDKhachHang");

                    b.HasIndex("IDHangKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanApi.Data.AnhSanPham", b =>
                {
                    b.Property<Guid>("IDAnhSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uuid");

                    b.Property<bool>("LaAnhChinh")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaAnh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IDAnhSanPham");

                    b.HasIndex("IDSanPhamChiTiet");

                    b.ToTable("AnhSanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("QuanApi.Data.BannerSanPham", b =>
                {
                    b.Property<Guid>("IDBannerSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BannerId")
                        .HasColumnType("integer");

                    b.Property<Guid>("IDSanPham")
                        .HasColumnType("uuid");

                    b.HasKey("IDBannerSanPham");

                    b.HasIndex("IDSanPham");

                    b.HasIndex("BannerId", "IDSanPham")
                        .IsUnique();

                    b.ToTable("BannerSanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.CauHinhBanHang", b =>
                {
                    b.Property<Guid>("IDCauHinhBanHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DanhSachQuanHuyenNoiThanh")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DiemToiDaSuDungMoiDon")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguonTinhPhiShipMacDinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("PhiShipMacDinh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhiShipNgoaiThanh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhiShipNoiThanh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhiShipToanQuoc")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoTienGiamTrenMotDiem")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoTienTrenMotDiemTich")
                        .HasColumnType("numeric");

                    b.Property<string>("TinhApDungPhiShip")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDCauHinhBanHang");

                    b.ToTable("CauHinhBanHangs");

                    b.HasData(
                        new
                        {
                            IDCauHinhBanHang = new Guid("8f3aa6f2-0608-4f47-a406-5de9ef3366d2"),
                            DanhSachQuanHuyenNoiThanh = "Ba Đình,Hoàn Kiếm,Tây Hồ,Long Biên,Cầu Giấy,Đống Đa,Hai Bà Trưng,Hoàng Mai,Thanh Xuân,Nam Từ Liêm,Bắc Từ Liêm,Hà Đông",
                            DiemToiDaSuDungMoiDon = 0,
                            NgayTao = new DateTime(2026, 4, 3, 7, 54, 53, 549, DateTimeKind.Utc).AddTicks(5852),
                            NguoiTao = "System",
                            NguonTinhPhiShipMacDinh = "Config",
                            PhiShipMacDinh = 50000m,
                            PhiShipNgoaiThanh = 35000m,
                            PhiShipNoiThanh = 20000m,
                            PhiShipToanQuoc = 50000m,
                            SoTienGiamTrenMotDiem = 1000m,
                            SoTienTrenMotDiemTich = 10000m,
                            TinhApDungPhiShip = "Hà Nội",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QuanApi.Data.ChatLieu", b =>
                {
                    b.Property<Guid>("IDChatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaChatLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDChatLieu");

                    b.ToTable("ChatLieus");
                });

            modelBuilder.Entity("QuanApi.Data.ChiTietGioHang", b =>
                {
                    b.Property<Guid>("IDChiTietGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("numeric");

                    b.Property<Guid>("IDGioHang")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaChiTietGioHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuongDatCho")
                        .HasColumnType("integer");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDChiTietGioHang");

                    b.HasIndex("IDGioHang");

                    b.HasIndex("IDSanPhamChiTiet");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("QuanApi.Data.ChiTietHoaDon", b =>
                {
                    b.Property<Guid>("IDChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric");

                    b.Property<Guid>("IDHoaDon")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaChiTietHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("numeric");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDChiTietHoaDon");

                    b.HasIndex("IDHoaDon");

                    b.HasIndex("IDSanPhamChiTiet");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.DanhMuc", b =>
                {
                    b.Property<Guid>("IDDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("QuanApi.Data.DiaChi", b =>
                {
                    b.Property<Guid>("IDDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DiaChiChiTiet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uuid");

                    b.Property<bool>("LaMacDinh")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaDiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SdtNguoiNhan")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDDiaChi");

                    b.HasIndex("IDKhachHang");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("QuanApi.Data.DotGiamGia", b =>
                {
                    b.Property<Guid>("IDDotGiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaDot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("integer");

                    b.Property<string>("TenDot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDDotGiamGia");

                    b.ToTable("DotGiamGias");
                });

            modelBuilder.Entity("QuanApi.Data.GioHang", b =>
                {
                    b.Property<Guid>("IDGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDKhachHang")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaGioHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDGioHang");

                    b.HasIndex("IDKhachHang");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("QuanApi.Data.HangKhachHang", b =>
                {
                    b.Property<Guid>("IDHangKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DiemDen")
                        .HasColumnType("integer");

                    b.Property<int>("DiemTu")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PhanTramGiamPhiShip")
                        .HasColumnType("numeric");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDHangKhachHang");

                    b.ToTable("HangKhachHangs");

                    b.HasData(
                        new
                        {
                            IDHangKhachHang = new Guid("d58c8c83-0f0a-48a8-a2dd-c7ac8f668f69"),
                            DiemDen = 499,
                            DiemTu = 0,
                            MaHang = "BRONZE",
                            NgayTao = new DateTime(2026, 4, 3, 7, 54, 53, 549, DateTimeKind.Utc).AddTicks(5875),
                            NguoiTao = "System",
                            PhanTramGiamPhiShip = 0m,
                            TenHang = "Đồng",
                            TrangThai = true
                        },
                        new
                        {
                            IDHangKhachHang = new Guid("49cb8a18-d15d-4df5-97be-f98f6ef88ca4"),
                            DiemDen = 1499,
                            DiemTu = 500,
                            MaHang = "SILVER",
                            NgayTao = new DateTime(2026, 4, 3, 7, 54, 53, 549, DateTimeKind.Utc).AddTicks(5879),
                            NguoiTao = "System",
                            PhanTramGiamPhiShip = 10m,
                            TenHang = "Bạc",
                            TrangThai = true
                        },
                        new
                        {
                            IDHangKhachHang = new Guid("b72f6741-bfd9-4c29-8aeb-6f4f2b8cbf3d"),
                            DiemDen = 2999,
                            DiemTu = 1500,
                            MaHang = "GOLD",
                            NgayTao = new DateTime(2026, 4, 3, 7, 54, 53, 549, DateTimeKind.Utc).AddTicks(5881),
                            NguoiTao = "System",
                            PhanTramGiamPhiShip = 20m,
                            TenHang = "Vàng",
                            TrangThai = true
                        },
                        new
                        {
                            IDHangKhachHang = new Guid("38fbce12-fc6f-4d1f-badf-fc2b70f6c396"),
                            DiemTu = 3000,
                            MaHang = "PLATINUM",
                            NgayTao = new DateTime(2026, 4, 3, 7, 54, 53, 549, DateTimeKind.Utc).AddTicks(5887),
                            NguoiTao = "System",
                            PhanTramGiamPhiShip = 30m,
                            TenHang = "Bạch kim",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QuanApi.Data.HoaDon", b =>
                {
                    b.Property<Guid>("IDHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BanTaiQuay")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaDatChoTonKho")
                        .HasColumnType("boolean");

                    b.Property<bool>("DaTruTonKho")
                        .HasColumnType("boolean");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("DiemCong")
                        .HasColumnType("integer");

                    b.Property<int>("DiemDaDung")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IDKhachHang")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDNhanVien")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDPhieuGiamGia")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDPhuongThucThanhToan")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LyDoHuyDon")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("PhiVanChuyen")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PhiVanChuyenGoc")
                        .HasColumnType("numeric");

                    b.Property<string>("SoDienThoaiNguoiNhan")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("SoTienGiamPhiVanChuyen")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SoTienGiamTuDiem")
                        .HasColumnType("numeric");

                    b.Property<string>("TenNguoiNhan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("TienGiam")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("numeric");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TrangThaiHoaDon")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TyLeQuyDoiDiem")
                        .HasColumnType("numeric");

                    b.HasKey("IDHoaDon");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVien");

                    b.HasIndex("IDPhieuGiamGia");

                    b.HasIndex("IDPhuongThucThanhToan");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.HoaTiet", b =>
                {
                    b.Property<Guid>("IDHoaTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaHoaTiet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenHoaTiet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDHoaTiet");

                    b.ToTable("HoaTiet");
                });

            modelBuilder.Entity("QuanApi.Data.KhachHangPhieuGiam", b =>
                {
                    b.Property<Guid>("IDKhachHangPhieuGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDPhieuGiamGia")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaKhachHangPhieuGiam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuongDaSuDung")
                        .HasColumnType("integer");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDKhachHangPhieuGiam");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDPhieuGiamGia");

                    b.ToTable("KhachHangPhieuGiams");
                });

            modelBuilder.Entity("QuanApi.Data.KichCo", b =>
                {
                    b.Property<Guid>("IDKichCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaKichCo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenKichCo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDKichCo");

                    b.ToTable("KichCos");
                });

            modelBuilder.Entity("QuanApi.Data.KieuDang", b =>
                {
                    b.Property<Guid>("IDKieuDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaKieuDang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenKieuDang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDKieuDang");

                    b.ToTable("KieuDangs");
                });

            modelBuilder.Entity("QuanApi.Data.LichSuDiemKhachHang", b =>
                {
                    b.Property<Guid>("IDLichSuDiemKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDHoaDon")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uuid");

                    b.Property<string>("LoaiBienDong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SoDiemBienDong")
                        .HasColumnType("integer");

                    b.Property<int>("SoDiemSau")
                        .HasColumnType("integer");

                    b.Property<int>("SoDiemTruoc")
                        .HasColumnType("integer");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDLichSuDiemKhachHang");

                    b.HasIndex("IDHoaDon");

                    b.HasIndex("IDKhachHang");

                    b.ToTable("LichSuDiemKhachHangs");
                });

            modelBuilder.Entity("QuanApi.Data.LichSuHoaDon", b =>
                {
                    b.Property<Guid>("IDLichSuHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<Guid>("IDHoaDon")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaLichSuHoaDon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TrangThaiLichSu")
                        .HasColumnType("boolean");

                    b.HasKey("IDLichSuHoaDon");

                    b.HasIndex("IDHoaDon");

                    b.ToTable("LichSuHoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.LoaiOng", b =>
                {
                    b.Property<Guid>("IDLoaiOng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaLoaiOng")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenLoaiOng")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDLoaiOng");

                    b.ToTable("LoaiOngs");
                });

            modelBuilder.Entity("QuanApi.Data.LungQuan", b =>
                {
                    b.Property<Guid>("IDLungQuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaLungQuan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenLungQuan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDLungQuan");

                    b.ToTable("LungQuans");
                });

            modelBuilder.Entity("QuanApi.Data.MauSac", b =>
                {
                    b.Property<Guid>("IDMauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaMauSac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDMauSac");

                    b.ToTable("MauSacs");
                });

            modelBuilder.Entity("QuanApi.Data.NhanVien", b =>
                {
                    b.Property<Guid>("IDNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("IDVaiTro")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDNhanVien");

                    b.HasIndex("IDVaiTro");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QuanApi.Data.PhieuGiamGia", b =>
                {
                    b.Property<Guid>("IDPhieuGiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DonToiThieu")
                        .HasColumnType("numeric");

                    b.Property<int>("GiaTriGiam")
                        .HasColumnType("integer");

                    b.Property<decimal?>("GiaTriGiamToiDa")
                        .HasColumnType("numeric");

                    b.Property<bool>("LaCongKhai")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("SoLuong")
                        .HasColumnType("smallint");

                    b.Property<string>("TenPhieu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDPhieuGiamGia");

                    b.ToTable("PhieuGiamGias");
                });

            modelBuilder.Entity("QuanApi.Data.PhongTroChuyen", b =>
                {
                    b.Property<Guid>("IDPhongTroChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDKhachHang")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDNhanVien")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaPhongTroChuyen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDPhongTroChuyen");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVien");

                    b.ToTable("PhongTroChuyens");
                });

            modelBuilder.Entity("QuanApi.Data.PhuongThucThanhToan", b =>
                {
                    b.Property<Guid>("IDPhuongThucThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaPhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDPhuongThucThanhToan");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("QuanApi.Data.SanPham", b =>
                {
                    b.Property<Guid>("IDSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CoGian")
                        .HasColumnType("boolean");

                    b.Property<bool>("CoXepLy")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IDChatLieu")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDDanhMuc")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDKieuDang")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDLoaiOng")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDLungQuan")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDThuongHieu")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDSanPham");

                    b.HasIndex("IDChatLieu");

                    b.HasIndex("IDDanhMuc");

                    b.HasIndex("IDKieuDang");

                    b.HasIndex("IDLoaiOng");

                    b.HasIndex("IDLungQuan");

                    b.HasIndex("IDThuongHieu");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamChiTiet", b =>
                {
                    b.Property<Guid>("IDSanPhamChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("IDDotGiamGia")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDHoaTiet")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDKichCo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDMauSac")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDSanPham")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaSPChiTiet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QRCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuongDatCho")
                        .HasColumnType("integer");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDSanPhamChiTiet");

                    b.HasIndex("IDDotGiamGia");

                    b.HasIndex("IDHoaTiet");

                    b.HasIndex("IDKichCo");

                    b.HasIndex("IDMauSac");

                    b.HasIndex("IDSanPham");

                    b.ToTable("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamDotGiam", b =>
                {
                    b.Property<Guid>("IDSanPhamDotGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("numeric");

                    b.Property<Guid>("IDDotGiamGia")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDSanPhamChiTiet")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaSanPhamDotGiam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDSanPhamDotGiam");

                    b.HasIndex("IDDotGiamGia");

                    b.HasIndex("IDSanPhamChiTiet");

                    b.ToTable("SanPhamDotGiams");
                });

            modelBuilder.Entity("QuanApi.Data.ThuongHieu", b =>
                {
                    b.Property<Guid>("IDThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaThuongHieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDThuongHieu");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("QuanApi.Data.TinNhan", b =>
                {
                    b.Property<Guid>("IDTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDKhachHang")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IDNhanVien")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IDPhongTroChuyen")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaTinNhan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasColumnType("text");

                    b.Property<string>("NguoiTao")
                        .HasColumnType("text");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDTinNhan");

                    b.HasIndex("IDKhachHang");

                    b.HasIndex("IDNhanVien");

                    b.HasIndex("IDPhongTroChuyen");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("QuanApi.Data.VaiTro", b =>
                {
                    b.Property<Guid>("IDVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LanCapNhatCuoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NguoiCapNhat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("IDVaiTro");

                    b.ToTable("VaiTro");

                    b.HasData(
                        new
                        {
                            IDVaiTro = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            MaVaiTro = "ADMIN",
                            NgayTao = new DateTime(2026, 4, 3, 7, 54, 53, 549, DateTimeKind.Utc).AddTicks(5751),
                            NguoiTao = "System",
                            TenVaiTro = "Quản trị viên",
                            TrangThai = true
                        },
                        new
                        {
                            IDVaiTro = new Guid("b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e"),
                            MaVaiTro = "NHANVIEN",
                            NgayTao = new DateTime(2026, 4, 3, 7, 54, 53, 549, DateTimeKind.Utc).AddTicks(5754),
                            NguoiTao = "System",
                            TenVaiTro = "Nhân viên",
                            TrangThai = true
                        },
                        new
                        {
                            IDVaiTro = new Guid("c3d4e5f6-a7b8-6c7d-0e1f-2a3b4c5d6e7f"),
                            MaVaiTro = "KHACHHANG",
                            NgayTao = new DateTime(2026, 4, 3, 7, 54, 53, 549, DateTimeKind.Utc).AddTicks(5769),
                            NguoiTao = "System",
                            TenVaiTro = "Khách hàng",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.HasOne("QuanApi.Data.HangKhachHang", "HangKhachHang")
                        .WithMany("KhachHangs")
                        .HasForeignKey("IDHangKhachHang")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HangKhachHang");
                });

            modelBuilder.Entity("QuanApi.Data.AnhSanPham", b =>
                {
                    b.HasOne("QuanApi.Data.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("AnhSanPhams")
                        .HasForeignKey("IDSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("QuanApi.Data.BannerSanPham", b =>
                {
                    b.HasOne("QuanApi.Data.Banner", "Banner")
                        .WithMany("BannerSanPhams")
                        .HasForeignKey("BannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.SanPham", "SanPham")
                        .WithMany("BannerSanPhams")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banner");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanApi.Data.ChiTietGioHang", b =>
                {
                    b.HasOne("QuanApi.Data.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("IDGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("IDSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("QuanApi.Data.ChiTietHoaDon", b =>
                {
                    b.HasOne("QuanApi.Data.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IDHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("IDSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("QuanApi.Data.DiaChi", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanApi.Data.GioHang", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("GioHangs")
                        .HasForeignKey("IDKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanApi.Data.HoaDon", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDKhachHang");

                    b.HasOne("QuanApi.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDNhanVien");

                    b.HasOne("QuanApi.Data.PhieuGiamGia", "PhieuGiamGia")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDPhieuGiamGia");

                    b.HasOne("QuanApi.Data.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("HoaDons")
                        .HasForeignKey("IDPhuongThucThanhToan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("PhieuGiamGia");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("QuanApi.Data.KhachHangPhieuGiam", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("KhachHangPhieuGiams")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.PhieuGiamGia", "PhieuGiamGia")
                        .WithMany("KhachHangPhieuGiams")
                        .HasForeignKey("IDPhieuGiamGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("PhieuGiamGia");
                });

            modelBuilder.Entity("QuanApi.Data.LichSuDiemKhachHang", b =>
                {
                    b.HasOne("QuanApi.Data.HoaDon", "HoaDon")
                        .WithMany("LichSuDiemKhachHangs")
                        .HasForeignKey("IDHoaDon")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("LichSuDiemKhachHangs")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanApi.Data.LichSuHoaDon", b =>
                {
                    b.HasOne("QuanApi.Data.HoaDon", "HoaDon")
                        .WithMany("LichSuHoaDons")
                        .HasForeignKey("IDHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanApi.Data.NhanVien", b =>
                {
                    b.HasOne("QuanApi.Data.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("IDVaiTro");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanApi.Data.PhongTroChuyen", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("PhongTroChuyens")
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.NhanVien", "NhanVien")
                        .WithMany("PhongTroChuyens")
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanApi.Data.SanPham", b =>
                {
                    b.HasOne("QuanApi.Data.ChatLieu", "ChatLieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.KieuDang", "KieuDang")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDKieuDang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.LoaiOng", "LoaiOng")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDLoaiOng")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.LungQuan", "LungQuan")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDLungQuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("IDThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatLieu");

                    b.Navigation("DanhMuc");

                    b.Navigation("KieuDang");

                    b.Navigation("LoaiOng");

                    b.Navigation("LungQuan");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamChiTiet", b =>
                {
                    b.HasOne("QuanApi.Data.DotGiamGia", "DotGiamGia")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDDotGiamGia");

                    b.HasOne("QuanApi.Data.HoaTiet", "HoaTiet")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDHoaTiet");

                    b.HasOne("QuanApi.Data.KichCo", "KichCo")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDKichCo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.MauSac", "MauSac")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.SanPham", "SanPham")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DotGiamGia");

                    b.Navigation("HoaTiet");

                    b.Navigation("KichCo");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamDotGiam", b =>
                {
                    b.HasOne("QuanApi.Data.DotGiamGia", "DotGiamGia")
                        .WithMany("SanPhamDotGiams")
                        .HasForeignKey("IDDotGiamGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanApi.Data.SanPhamChiTiet", "SanPhamChiTiet")
                        .WithMany("SanPhamDotGiams")
                        .HasForeignKey("IDSanPhamChiTiet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DotGiamGia");

                    b.Navigation("SanPhamChiTiet");
                });

            modelBuilder.Entity("QuanApi.Data.TinNhan", b =>
                {
                    b.HasOne("KhachHang", "KhachHang")
                        .WithMany("TinNhans")
                        .HasForeignKey("IDKhachHang");

                    b.HasOne("QuanApi.Data.NhanVien", "NhanVien")
                        .WithMany("TinNhans")
                        .HasForeignKey("IDNhanVien");

                    b.HasOne("QuanApi.Data.PhongTroChuyen", "PhongTroChuyen")
                        .WithMany("TinNhans")
                        .HasForeignKey("IDPhongTroChuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("PhongTroChuyen");
                });

            modelBuilder.Entity("KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");

                    b.Navigation("KhachHangPhieuGiams");

                    b.Navigation("LichSuDiemKhachHangs");

                    b.Navigation("PhongTroChuyens");

                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("QuanApi.Data.Banner", b =>
                {
                    b.Navigation("BannerSanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.ChatLieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.DotGiamGia", b =>
                {
                    b.Navigation("SanPhamChiTiets");

                    b.Navigation("SanPhamDotGiams");
                });

            modelBuilder.Entity("QuanApi.Data.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("QuanApi.Data.HangKhachHang", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("QuanApi.Data.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("LichSuDiemKhachHangs");

                    b.Navigation("LichSuHoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.HoaTiet", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.KichCo", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.KieuDang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.LoaiOng", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.LungQuan", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhongTroChuyens");

                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("QuanApi.Data.PhieuGiamGia", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("KhachHangPhieuGiams");
                });

            modelBuilder.Entity("QuanApi.Data.PhongTroChuyen", b =>
                {
                    b.Navigation("TinNhans");
                });

            modelBuilder.Entity("QuanApi.Data.PhuongThucThanhToan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanApi.Data.SanPham", b =>
                {
                    b.Navigation("BannerSanPhams");

                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("QuanApi.Data.SanPhamChiTiet", b =>
                {
                    b.Navigation("AnhSanPhams");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("SanPhamDotGiams");
                });

            modelBuilder.Entity("QuanApi.Data.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanApi.Data.VaiTro", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
