<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Compile Remove="Services\**" />
    <Compile Remove="ViewModels\**" />
    <Content Remove="Controllers\**" />
    <Content Remove="Services\**" />
    <Content Remove="ViewModels\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <None Remove="Controllers\**" />
    <None Remove="Services\**" />
    <None Remove="ViewModels\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Services\IChatLieuService.cs" />
    <Compile Include="Services\IEmailService.cs" />
    <Compile Include="Services\IKichCoService.cs" />
    <Compile Include="Services\IKieuDangService.cs" />
    <Compile Include="Services\IVnPayService.cs" />
    <Compile Include="Services\VnPayLibraryApi.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Views\BaoCaoThongKe\" />
    <Folder Include="Areas\Admin\Views\ChatLieu\" />
    <Folder Include="Areas\Admin\Views\ClientBanHangTaiQuay\" />
    <Folder Include="Areas\Admin\Views\HoaTiet\" />
    <Folder Include="Areas\Admin\Views\KhachHang\" />
    <Folder Include="Areas\Admin\Views\KichCo\" />
    <Folder Include="Areas\Admin\Views\KieuDang\" />
    <Folder Include="Areas\Admin\Views\LoaiOng\" />
    <Folder Include="Areas\Admin\Views\LungQuan\" />
    <Folder Include="Areas\Admin\Views\MauSac\" />
    <Folder Include="Areas\Admin\Views\NhanViens\" />
    <Folder Include="Areas\Admin\Views\ProductManage\" />
    <Folder Include="Areas\Admin\Views\QuanLyDonHang\" />
    <Folder Include="Areas\Admin\Views\SanPham\" />
    <Folder Include="Views\Checkout\" />
    <Folder Include="Views\DonHang\" />
    <Folder Include="Views\GioHang\" />
    <Folder Include="Views\Home\" />
    <Folder Include="Views\Login\" />
    <Folder Include="Views\SanPhamNguoiDung\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0" />
    <PackageReference Include="MimeKit" Version="4.13.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuanApi\QuanApi.csproj" />
  </ItemGroup>

</Project>
